### ISSUE TITLE
App getting crashed frequently

### ISSUE THREAD

**Issue by bhargav015** [just-ai/aimybox-android-sdk#102]
Hello, We are using Aimybox from a while, But suddenly we start facing the issue of app crash very frequently with below error. Please help us as soon as possible

`java.io.IOException: Read 0 bytes from recorder
        at com.justai.aimybox.recorder.AudioRecorder$startRecordingBytes$1.invokeSuspend(AudioRecorder.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by bgubanov** [comment]
Hello. Can you provide version of Android? I suppose, exception is thrown when you try to activate speech recognizing? Please describe the issue in more detail
