### ISSUE TITLE
Прерывание распознавания речи.

### ISSUE THREAD

**Issue by svetlana-e-petrova** [just-ai/aimybox-android-sdk#96]
У нас в приложении необходимо поддерживать следующие сценарии:

1. Если идет синтез речи (State.SPEAKING), при клике на кнопку распознавания нужно прервать речь и активировать распознование.
2. Если происходит распознавание речи (State.LISTENING), при клике на кнопку распознавания нужно прервать распознавание и отправить запрос с уже распознанным текстом.
3. Для увеличения скорости диалога необходимо сократить паузу в конце распознавания (когда State.LISTENING, но человек уже закончил говорить). 

Для прерывания/переключения состояния распознавания в aimybox есть следующие методы: stopRecognition(), cancelRecognition(), toggleRecognition(). 

Для реализации 1 и 2 сценария мы вызываем toggleRecognition() при клике на кнопку распознавания + подписываемся на событие SpeechToText.Event.RecognitionCancelled - когда, оно прилетает, вызываем метод Aimybox sendRequest(query: String) с последним распознанным текстом. 
В чем проблема: в большинстве случаев сценарии корректно отрабатывают, но есть случаи, когда 1) из-за прерывания распознавания неправильно прерывается метод send() в DialogApi и вызывает ошибку «kotlinx.coroutines.JobCancellationException: UndispatchedCoroutine was cancelled» - в результате в логах чередуются зафейлившийся и успешный запрос; 2) распознавание прерывается, но отправляется два запроса, в результате на экране дублируются и запрос и ответ; 3) запрос вообще не отправляется - в результате на экране повисает последний распознанный текст без ответа.

Для реализации сценария 3 мы смотрим на события, которые прилетают в speechToTextEvents, считаем количество событий AudioBufferReceived между событиями RecognitionPartialResult и, если их становится больше некой константы (сейчас у нас 3), то вручную прерываем распознавание. Для прерывания пробовали использовать каждый из трех методов stopRecognition(), cancelRecognition(), toggleRecognition(). cancelRecognition() и toggleRecognition() вызывают те же проблемы, что и в сценариях 1 и 2, только в бОльшем маштабе, т.к. это срабатывает при каждом запросе, а не только при нажатии на кнопку. А использование метода stopRecognition() крашит приложение со следующим стектрейсом: 
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler ChildCompletion[ChildHandle[StandaloneCoroutine{Completed}@a92f170], kotlin.Unit] for StandaloneCoroutine{Completed}@a92f170
 at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1533)
 at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
 at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
 at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
 at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
 at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: call already half-closed
 at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
 at io.grpc.internal.ClientCallImpl.halfCloseInternal(ClientCallImpl.java:491)
 at io.grpc.internal.ClientCallImpl.halfClose(ClientCallImpl.java:482)
 at io.grpc.internal.DelayedClientCall$6.run(DelayedClientCall.java:361)
 at io.grpc.internal.DelayedClientCall.delayOrExecute(DelayedClientCall.java:248)
 at io.grpc.internal.DelayedClientCall.halfClose(DelayedClientCall.java:358)
 at io.grpc.PartialForwardingClientCall.halfClose(PartialForwardingClientCall.java:44)
 at io.grpc.ForwardingClientCall.halfClose(ForwardingClientCall.java:22)
 at io.grpc.ForwardingClientCall$SimpleForwardingClientCall.halfClose(ForwardingClientCall.java:44)
 at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onCompleted(ClientCalls.java:375)
 at com.justai.aimybox.speechkit.yandex.cloud.YandexSpeechToText$startRecognition$1$2.invoke(YandexSpeechToText.kt:60)
 at com.justai.aimybox.speechkit.yandex.cloud.YandexSpeechToText$startRecognition$1$2.invoke(YandexSpeechToText.kt:17)
 at kotlinx.coroutines.channels.AbstractSendChannel.invokeOnCloseHandler(AbstractChannel.kt:268)
 at kotlinx.coroutines.channels.AbstractSendChannel.close(AbstractChannel.kt:258)
 at kotlinx.coroutines.channels.SendChannel$DefaultImpls.close$default(Channel.kt:102)
 at kotlinx.coroutines.channels.ProducerCoroutine.onCompleted(Produce.kt:137)
 at kotlinx.coroutines.channels.ProducerCoroutine.onCompleted(Produce.kt:130)
 at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:104)
 at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:235)
 at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
 at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
 at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
 at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1529)
 ... 12 more

**Comment by bgubanov** [comment]
1. Данный сценарий изначально был заложен при разработке системы
Для пунктов 2 и 3 была совершены доработки:
Чтобы изменить поведение системы во втором сценарии, необходимо изменить параметр при конфигурации Aimybox
```kotlin 
Config.create(speechToText, textToSpeech, dialogApi) {
    stopRecognitionBehavior = Config.StopRecognitionBehavior.PROCESS_REQUEST
}
```
Для третьего сценария необходимо при инициализации STT в конструкторе задать новый параметр `maxAudioChunks `  (стандартное значение `null`)
```kotlin
YandexSpeechToText(tokenGenerator, folderId, Language.RU, maxAudioChunks = 5)
```
Происходит то же самое: система смотрит на количество аудио чанков между распознанным текстом и при превышении лимита останавливает распознавание.
Данные изменения можно увидеть в новом снапшоте
```kotlin
implementation("com.just-ai.aimybox:core:0.16.4.2-SNAPSHOT")
```
Доступно в репозитории снапшотов:
```kotlin
repositories {
    /* */
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}
```

**Comment by svetlana-e-petrova** [comment]
@bgubanov Добрый день! Со второй частью возникла проблема - не удается передать maxAudioChunks в STT. 
Конструктор `YandexSpeechToText` не позволяет прокинуть в SpeechToText этот параметр. 
```
class YandexSpeechToText(
    iAmTokenProvider: IAmTokenProvider,
    folderId: String,
    language: Language,
    config: Config = Config()
) : SpeechToText()
```
Нужно  либо внести правки в конструктор 'YandexSpeechToText' и для com.justai.aimybox:yandex-speechkit тоже снапшот делать, либо добавить сеттер для 'maxAudioChunks' в класс `SpeechToText`.
